*Importando as bibliotecas*

In [4]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Data Base

In [70]:
db = pd.read_csv('data/products-1000.csv')
db.describe()

             Index        Price        Stock           EAN  Internal ID
count  1000.000000  1000.000000  1000.000000  1.000000e+03  1000.000000
mean    500.500000   506.549000   501.782000  5.130255e+12    47.690000
std     288.819436   283.773556   292.151318  2.907413e+12    28.984202
min       1.000000     1.000000     2.000000  4.842647e+08     1.000000
25%     250.750000   284.750000   243.000000  2.699217e+12    22.000000
50%     500.500000   497.500000   504.000000  5.118167e+12    46.000000
75%     750.250000   757.250000   750.250000  7.653439e+12    74.000000
max    1000.000000   999.000000   999.000000  9.994627e+12    99.000000

Média

In [67]:
#falta
print(f"A média dos preços é: ${db['Price'].mean().round(2)}")

A média dos preços é: $506.55

Mediana

In [ ]:
#falta
print(f"A mediana dos preços é: ${db['Price'].median()}")

A mediana dos preços é: $497.5

Moda

In [ ]:
#falta
moda_size = db['Size'].mode()[0]
print(f"A moda dos tamanhos é: {moda_size}")

A moda dos tamanhos é:8x10 in

Max

In [ ]:
#falta
print(f"O preço máximo é: ${db['Price'].max()}")

O preço máximo é: $999

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
16,17,Digital Clock Lock Eco Premium Portable,On ago smile stop.,Leonard LLC,Office Supplies,999,USD,14,1286011880117,SeaShell,XL,in_stock,83

Min

In [ ]:
#falta
print(f"O preço mínimo é: ${db['Price'].min()}")

O preço mínimo é: $1

Desvio

In [64]:
#falta
print(f"O desvio padrão é: ${db['Price'].std().round(2)}")

O desvio padrão é: $283.77